chat.php

User Avy's should pop up to right of their name/village
Unsure if this will work in all cases / or for all viewing devices - CSS has hard coded values such as 'margin: 10% 0px'; etc

Chat.php - Avy's in Chat

---

battleCore.php

- edits in battleCore.php
- not sure if this works in pvp

Added Color to Damage Text

---

classes/user.php
scripts/functions.js

-Webpage Title blinks when user training finishes
-Unsure if this works in all cases (jutsu training, etc)

Training Title Bar notification

---

chat.php
healingShop.php

Fixed warnings for keys post, delete, and min

Update chat and ramen shop

---

store.php

-added column to show the jutsu type
-fixed some left aligned items in Gear and Consumables

Added JutsuType Column in shop

---

arena.php
battleCore.php
chat.php
classes/system.php
layout/cextralite.php
style/cextralite/responsive_script.js
style/cextralite/style.css

- added script file
- changes some html placements
- AK page menu missing

Mobile CSS - Menu Update

---

classes/User.php
premium.php
register.php

Stat transfers under 10 are free, however there is a 24 hour cool down
AK cost dynamically changes if below 10.
Fixed bug where default skill would be ninjutsu selected if above rank 2.
Default rank 1 skill is ninjutsu.
.

Stat transfer changes

---

index.php
modPanel.php
notifications.php
style/blue_scroll/layout.css

- Switch to Shadow Ribbon-style notifications.
- Shortened the banner.

Fixed Blue Scroll Notifications

---

settings.php

Fixed password change error.
Fixed endless reload on layout change.

Settings Page Fixes

---

classes/User.php

Blacklist error

---

manual.php

Gojo provided a lot of info from a large google document and I spent 
some time formatting it for html. This is just initial commit for users 
to have, still need to go over it and make it look better

Manual Edits - Provided by Gojo

---

members.php

Top pvp page [Issue #89] and various other fixes along the way

---

members.php
style/classic_blue/style.css

changed top 10 to top 15. added top 15 teams

---

arena.php
battle.php
classes/User.php

transported to village if you die/draw to ai

---

classes/SupportManager.php
modPanel.php
password_reset.php
premium.php
support.php
supportPanel.php
templates/displayTicket.php
templates/guestSupport.php
templates/staff/supportRequests.php

Upgraded support system as discussed.
Support type statics not being used everywhere
Added functionality for staff to re-open supports
Corrected bug where comments wouldn't go through when closing or opening a support

Support System Upgrade.

---

chat.php
classes/User.php
classes/battle/BattleManager.php
db/migrations/premium_change.sql
premium.php
templates/premium.php

Premium bug fix v2

---

privateMessages.php

PM display fix.
Old:
Reworked:

PM line wrap fix

---

.gitignore
pages/chat.php
pages/privateMessages.php
pages/settings.php

Added functionality to display a character counter when message box gets within 20 remaining characters of specified limit. This applies to the chat, journal, and private messages.

Chat, Journal, and Private Message Character Remaining Counter

---

classes/User.php
pages/travel.php

Added int parsing for player x and y. Set village check to strict equivalence.

Fix bug with village location check returning true for 16.1 and 16.10.

---

classes/Inbox.php
classes/InboxManager.php
pages/inbox.php
templates/inbox.php
ui_components/build/inbox/inbox.js
ui_components/build/inbox/util.js
ui_components/build/utils/formData.js
ui_components/src/inbox/inbox.js

-- Fixed a bug preventing changes to the conversation by the owner
-- Fixed a bug that sends the user to a 404 when selecting profile links in the conversation details list
-- Clicking the send message button on user profile's now shows a prompt for a new conversation

Inbox Overhaul Fixes

---

ajax_notifications.php

-- Defines the new_message variables that cause the ajax notification to fail

Fixing Notification Bug with New Messages

---

classes/Mission.php
pages/missions.php

This will lock players in battle during survival missions preventing them from being attacked or accidentally moving without retreating.

Survival missions now lock the user in battle

---

pages/missions.php

Prevent survival mission state changes unless it's a survival mission.

Fix bug with survival missions.

---

api/inbox.php
classes/Inbox.php
classes/InboxManager.php
db/migrations/20230116_inbox_mute.sql
pages/inbox.php
style/blue_scroll/layout.css
ui_components/build/inbox/ConversationList.js
ui_components/build/inbox/inbox.js
ui_components/src/inbox/ConversationList.js
ui_components/src/inbox/inbox.js

-- Adds an option for users to mute notifications for each conversation. 
-- Properly shows system alerts as read or unread.
-- Now marks a message read for the user when creating a new conversation.

Inbox Mute Function

---

classes/ForbiddenSeal.php

Fixed training time bug associated with forbidden seal

---

manual.php

Made the manual prettier
Included bloodline_list.php in Bloodline section, because as a Academy student I had no way of getting any BL information and it should be included in manual.

fix: updated manual UI and added bloodline list

---

classes/Inbox.php
classes/ReportManager.php
classes/StaffManager.php
classes/User.php
db/migrations/20230127_staff_rework.sql
index.php
notifications.php
pages/chat.php
pages/inbox.php
pages/members.php
pages/modPanel.php
pages/report.php
pages/settings.php
templates/ban_info.php
templates/inbox.php
templates/settings.php
templates/staff/mod/ban_confirm.php
templates/staff/mod/banned_ips.php
templates/staff/mod/banned_users.php
templates/staff/mod/head_mod_menu.php
templates/staff/mod/locked_out_users.php
templates/staff/mod/mod_menu.php
templates/staff/mod/mod_panel_header.php
templates/staff/mod/official_warning.php
templates/staff/mod/report_submenu.php
templates/staff/mod/unban_confirm.php
templates/staff/mod/view_all_reports.php
templates/staff/mod/view_record.php
templates/staff/mod/view_report.php
templates/submit_report.php

Mod panel upgrade is complete. Ready for review.

Staff rework

---

classes/RankManager.php
classes/StaffManager.php
classes/System.php
classes/User.php
db/migrations/20230225_staff_fixes.sql
notifications.php
pages/adminPanel.php
pages/chat.php
pages/chat_log.php
pages/levelUp.php
pages/modPanel.php
pages/report.php
routes.php
templates/admin/logs.php
templates/admin/stat_cut.php
templates/staff/mod/chat_log.php
templates/staff/mod/head_mod_menu.php
templates/staff/mod/mod_logs.php
templates/staff/mod/multi_accounts.php
templates/staff/mod/view_report.php

Fixed issues and made recommended changes.

Staff upgrade fixes.

---

classes/Inbox.php
classes/StaffManager.php
classes/User.php
pages/adminPanel.php
pages/chat.php
pages/modPanel.php
templates/chat.php
templates/settings.php
templates/staff/mod/head_mod_menu.php
templates/staff/mod/mod_menu.php
templates/staff/mod/view_record.php

Fixed cosmetic display issues for new staff menus.
Fixed error in not removing elements when necessary for stat cuts Fixed Inbox to allow special char display
Fixed table display issue in user records
Fixed grammatical errors in staff logs
Added globals to staff logs

Cosmetic & grammatical fixes

---

classes/Mission.php
pages/chat.php
templates/chat.php

Fixed gap between avatar and staff banner
Increased avatar size from 45x45 -> 75x75 (looks better imo)
Fixed issue where line breaks were not being added
Reverted chat back to using default of 1 min(s) ago, due to unpopularity of the < 1 min text

Chat changes & Team Mission Bug Patch

---

templates/battle/battle_interface.php
templates/chat.php

Fix some overflowing of div in chat when images are too large. Also fix css getting ignored on battle page for avatar sizes.

Fixes for avatar size and long name wrapping.

---

admin/formTools.php
backfills/bloodline_jutsu_fix.php
backfills/user_health_and_level.php
classes/User.php
pages/adminPanel.php

Fixed 500 errors on backfill pages.
Added support to change elements in the admin panel.

Admin fixes

---

classes/Notifications.php
notifications.php
pages/inbox.php

Notifications now work as intended (added OWs, reports and moved PM check to the notification check method.
Added partial support for blacklists (1-on-1 chats, group chats still fully allowed).

Notifications & BL partial fix

---

classes/ForbiddenSeal.php
pages/premium.php

Converts premium time remaining to AK with following ratios of days->AK rounding down:
Twin Sparrow Seal -> 6:1
Four Dragon Seal -> 2:1

Apply AK credit from existing premium time when changing seal.

---

classes/battle/BattleEffectsManager.php

Initial changes for functionality - can refactor to scrub fighter->cast_speed_nerf and references

Consolidate speed/cspeed nerf initial change

---

pages/jutsu.php
templates/chat.php

Disregard stroke in commit title

Fix jutsu page null check on ninjutsu

---

templates/chat.php

Sample with default layout:
Has some changes from auto-format.

Meme modal fix

---

pages/jutsu.php
templates/jutsu_page.php

Retains existing equip/learn/forget functionality.
Sample of jutsu view:

Jutsu page overhaul

---

classes.php
classes/Notifications.php
classes/Router.php
classes/SenseiManager.php
classes/User.php
db/migrations/20230512113441_sensei_migration.php
pages/levelUp.php
pages/premium.php
pages/profile.php
pages/training.php
pages/villageHQ.php
templates/profile.php
templates/sensei.php
templates/sensei_exam.php
templates/view_user_profile.php

Imgur gallery: https://imgur.com/a/FqdeChM (minor styling tweaks since)
Test cases used:
```
All Players:
VillageHQ
- Sensei tab to nav: display sensei detail listing with link to sensei/student profiles, restricted by village and sorted by graduated count
Akademi/Genin:
Profile
- Not Student: Display section with link to VillageHQ->Sensei
- Is Student: Display section with sensei details, link to sensei/student profiles
VillageHQ
- Display informational section
- Has active application: display grid with link to sensei, link to revoke application
- Actions:
- Apply: check if already have sensei, rank, if target player is sensei, village, accepting students, error if student roster full or duplicate application, create notification for sensei
- Cancel Application
- Leave Sensei
Members
- …
```

Sensei Update

---

classes/Router.php
classes/notification/NotificationAPIManager.php
classes/travel/TravelManager.php
pages/clan.php
pages/missions.php
pages/premium.php
pages/team.php
templates/level_rank_up/chuunin_written_exam.php
ui_components/build/chat/Chat_new.js
ui_components/build/topbar/Topbar.js
ui_components/build/topbar/TopbarNotification.js
ui_components/src/chat/Chat_new.js
ui_components/src/notificationSchema.js
ui_components/src/topbar/Topbar.css
ui_components/src/topbar/Topbar.js
ui_components/src/topbar/TopbarNotification.js

- Chuunin exam (remove deleted reference)
- Add training notification to ancient market
- Fix case on link to latest post
- Fix training display if timer goes negative
- Remove map location for "search" missions
- Fix mission notification display
- Prevent joining team mission if already on mission

Fix Chuunin Exam, misc fixes

---

style/new_geisha/new_geisha.css
style/sidebar_right.css
templates/header.php
templates/sidebar.php
ui_components/build/header/Header.js
ui_components/build/sidebar/Sidebar.js
ui_components/src/chat/Chat_new.css
ui_components/src/header/Header.css
ui_components/src/header/Header.js
ui_components/src/sidebar/Sidebar.css
ui_components/src/sidebar/Sidebar.js

Restructure Login/Header

---

classes.php
classes/Notifications.php
classes/SenseiManager.php
classes/notification/NotificationAPIManager.php
classes/training/TrainingManager.php
db/migrations/20230620062917_sensei_lesson_migration.php
pages/members.php
pages/premium.php
pages/profile.php
pages/specialmissions.php
pages/training.php
pages/villageHQ.php
templates/profile.php
templates/sensei.php
templates/sensei_exam.php
templates/view_user_profile.php

- Sensei are considered specialized in their bloodline
- Fix cast speed specialization display
- Sensei set to inactive instead of deleted to preserve data

Sensei tweaks, Training Feature

---

classes/Layout.php
classes/SpecialMissions.php
classes/System.php
classes/User.php
classes/travel/TravelManager.php
index.php
layout/_common.php
pages/premium.php
pages/profile.php
style/new_geisha/new_geisha.css
templates/profile_v2.php
templates/sensei.php
ui_components/build/CharacterAvatar.js
ui_components/build/profile/Profile.js
ui_components/build/sidebar/Sidebar.js
ui_components/src/CharacterAvatar.js
ui_components/src/_schema/userSchema.js
ui_components/src/home/Home.css
ui_components/src/profile/Profile.css
ui_components/src/profile/Profile.js
ui_components/src/sidebar/Sidebar.js

Reusable character avatar component is here, also finally got around to making a `$system->isDevEnvironment()` helper method
Progress so far:

New profile skeleton

---

admin/entity_constraints.php
admin/formTools.php
classes/NPC.php
classes/System.php
classes/battle/BattleManager.php
pages/arena.php
pages/event.php
templates/temp_event.php
ui_components/build/topbar/TopbarNotification.js
ui_components/src/topbar/Topbar.css
ui_components/src/topbar/TopbarNotification.js

Add "disabled" radio button for arrays of optional length.
e.g. Mission -> Stage has up to 4 "optional" but all are required on edit, can now mark individual stage as "disabled".

Complete Event Functionality + AI Tweaks

---

classes/SpecialMissions.php
classes/Village.php
pages/arena.php
templates/specialMissions.php

Add rep gain for special missions

Reputation 2.2

---

templates/home.php
ui_components/build/profile/Profile.js
ui_components/src/profile/Profile.css
ui_components/src/profile/Profile.js

Make stats responsive, move profile image

Profile tweaks

---

classes/User.php
classes/battle/BattleEffectsManager.php

Putting these suggestions here for your thoughts.

Scale BL jutsu with rank at half rate, restrict offense boost to highest

---

db/migrations/20230817004323_forbidden_mission_migration.php
style/new_geisha/new_geisha.css
templates/jutsu_page.php
ui_components/build/sidebar/Sidebar.js
ui_components/src/sidebar/Sidebar.css
ui_components/src/sidebar/Sidebar.js
ui_components/src/topbar/Topbar.css

Mobile tweaks

---

style/new_geisha/new_geisha.css
ui_components/build/sidebar/Sidebar.js
ui_components/src/sidebar/Sidebar.css
ui_components/src/sidebar/Sidebar.js

https://images-ext-1.discordapp.net/external/P2Klr_j8XJC25l3y7TckkALsGp-Zuad3005iVXQKYJk/https/i.imgur.com/k4KDcS0.png

Mobile adjustment, static collapsed nav on top

---

classes/Mission.php
classes/User.php
classes/Village.php

Fixed issue with missions displaying incorrect search/previous location
Fixed issue with mission notifications showing incorrect information
Restructured Village initialization logic / added helpers for resource mechanics
`villages`.`resources` will be added with 1st draft war mechanics

Mission bug fixes, Village rework

---

templates/bloodlineList.php

Should be possible to filter Bloodlines by their Jutsu Type. 
___
If a bloodline has a jutsu type with 'fire', then bloodlines with jutsu element of 'fire' will show. 
Filtering is done by adding a class name to the <td> html elements during the php construction foreach loop, and then using the <select onchange> event to filter out classes that have the jutsu element types. 
- One issue is <td> elements can have more than one class of the same name like <td classname='fire fire none'>

Filter Bloodline by Jutsu Type

---

api/battle.php
classes/UserReputation.php
classes/battle/BattleEffectsManager.php
classes/travel/MapLocation.php
classes/travel/TravelManager.php
layout/_common.php
layout/new_geisha.php
layout/sumu.php
pages/bloodline.php
pages/forbiddenShop.php
pages/spar.php
scripts/react-transition-group.js
style/new_geisha/new_geisha.css
templates/battle/battle_interface.php
ui_components/build/chat/Chat_new.js
ui_components/build/topbar/Topbar.js
ui_components/build/topbar/TopbarNotification.js
ui_components/build/travel/Map.js
ui_components/src/chat/Chat_new.js
ui_components/src/topbar/Topbar.js
ui_components/src/topbar/TopbarNotification.js
ui_components/src/travel/Map.js
ui_components/src/travel/Travel.css

- Enable Ayakashi's Abyss during events
- Battle timer for spectate now refreshes correctly
- Battle timer during pre-heal now counts down correctly
- Fixed style for invulnerable players
- Fixed style for chat buttons
- PvE Rep CD from 60s -> 30s
- Rep from Spars now works in village as well (same-village players running to colosseum is counterintuitive)
- Moved delete button away from quote button (mods accidentally press)
- Fix rounding of bloodline boost on bloodline page
- Notification close on click
- Host `react-transition-group.js` directly (fix site loading slow)

v0.9.2 Bugs/Tweaks

---

pages/bloodline.php
style/new_geisha/new_geisha.css
templates/jutsu_page.php
ui_components/src/travel/Travel.css

- Minimum travel button width
- Travel button stack vertically
- Rounding on bloodline page
- Jutsu dropdown size
- New Geisha button style

Style Tweaks

---

classes/ForbiddenSeal.php
classes/System.php
classes/User.php
classes/UserReputation.php
classes/event/DoubleReputation.php
classes/event/DoubleReputationEvent.php
manual.php
templates/premium/premium.php
templates/temp_event.php

Added double reputation event
Added +1 static FS reputation

Reputation changes

---

classes/System.php
classes/UserReputation.php

Reputation debug
Bug fix for rep rank changes (cosmetic display only)

Reputation bug fix

---

classes/chat/ChatManager.php
classes/travel/RegionObjective.php
classes/travel/TravelApiPresenter.php
classes/travel/TravelManager.php
classes/war/Operation.php
classes/war/WarManager.php
ui_components/build/travel/Map.js
ui_components/src/travel/Map.js
ui_components/src/travel/Travel.css

- Display for captured towns
- Captured towns lootable by ally
- Fix bug with protected allies (on my fresh install, breaks travel without checking for null)

Town Capture Tweaks

---

classes/travel/TravelManager.php
classes/village/VillageManager.php
classes/war/WarManager.php
pages/battle.php

- Fix Chuunin vs Chuunin attacks being blocked by Jonin protection
- Visual: Fix yen symbol on deposit resources
- Visual: Remove debug number on battle end
- Visual: Account for occupied villages in supply points count

War Bug Fixes

---

classes/war/WarLogDto.php
classes/war/WarLogManager.php
ui_components/build/village/Village.js
ui_components/src/village/Village.css
ui_components/src/village/Village.js

- Refactor `WarLogDto` constructor with single-line assignment
- When getting player totals, add total from history with all villages (not just latest village)
- Fix Lsmjudoka display bug
- Add village icon to war logs

WarLog Refactor + Fix

---

classes.php
classes/System.php
classes/User.php
classes/chat/ChatAPIPresenter.php
classes/chat/ChatManager.php
classes/chat/ChatPostDto.php
classes/inbox/Inbox.php
classes/inbox/InboxUser.php
classes/user/Blacklist.php
db/migrations/20231102052648_blacklist_misc_changes.php
index.php
pages/inbox.php
pages/marriage.php
pages/sendMoney.php
pages/settings.php
templates/settings.php

**Blacklist Update**
Blacklist now works in Inbox (direct messages) as it does in chat, by hiding blocked users in pre-existing multi-chats.
Note: This may lead to "ghost" notifications should someone on your BL post in the group DM.
**Account Lockout Change**
Account lockouts will now function differently than they did in the past.
Failing to login from new location 3 or more times will result in a 5 minute cooldown period before you can login again (this will stack to 8 - 10 minutes with two additional fails in a 10 minute period).
Failing to login from a previous location (last two recorded) will result in a 3 minute cooldown period before you can login again.
Head Moderators and User Admins can still manually unlock accounts to bypass this cooldown period.

Blacklist & Lockout QoL

---

classes/PremiumShopManager.php
pages/jutsu.php
pages/store.php
templates/premium/character_changes.php

On Dev:
- Ignore parent jutsu requirement to learn
- Learned jutsu set to level 100
- Stat transfer time 0 seconds
- Stat transfer cost 0 yen
- Stat transfer cost 0 AK
- Change element cost 0 AK
- Change village cost 0 AK
- Change bloodline cost 0 AK

Dev Flags for Playtest

---

classes/Bloodline.php
classes/battle/BattleEffectsManager.php
classes/battle/BattleManager.php
classes/battle/Fighter.php
pages/bloodline.php
pages/healingShop.php
pages/store.php

- Dev flags
- Code fixes (some manually on dev already)
- Tuned speed ratio value
- Reworked BL jutsu scaling
- 0.9x Off Skill and 0.6x BL Skill (from 0.8x and 0.8x) 
- BL builds now tradeoff approximately 10% shop damage in exchange for approximately 20% BL jutsu damage
- For balanced builds BL jutsu will be similar damage for the same power (e.g. 4.4 shop jutsu = 4.4 BL jutsu)

Combat Tweaks

---

classes/System.php
pages/levelUp.php

- Increase Elite chances to 20% (so players have total 25% chance to roll Elite or Legendary)
- Add link to ancient market in Genin exam results

Bloodline rolls

---

classes/System.php
classes/User.php
classes/event/BonusExpWeekend.php
classes/event/DoubleExpEvent.php
classes/event/Event.php
classes/training/TrainingManager.php
templates/temp_event.php
templates/training.php

- Add +50% bonus XP on weekends if no other event active
- Jutsu training affected by bonus XP

Weekend event

---

api/battle.php
classes/battle/Battle.php
classes/battle/BattleAttack.php
classes/battle/BattleEffectsManager.php
classes/battle/BattleManager.php
classes/travel/Travel.php
style/new_geisha/new_geisha.css
style/sumu/sumu.css
templates/battle/action_prompt.php
templates/battle/battle_interface.php
templates/bloodlineList.php
templates/jutsu_page.php
templates/store.php

Combat v1.2 updates 5

---

classes/Team.php
classes/User.php
classes/battle/Battle.php
classes/battle/Fighter.php

- ~~Reputation bonus in challenges reduced to 5% per tier~~
- Removed hidden team boost to damage taken

Misc Damage Reduction Tweaks

---

classes/battle/BattleManager.php
classes/battle/Fighter.php

- Reverted Immolate to previous version
- Calculate recoil using final damage dealt
- Fixed bug with resists that would apply soft cap reduction on each instance of damage taken

Combat Adjustments

---

admin/user.php
classes/StaffManager.php
pages/adminPanel.php
templates/admin/reset_password.php

Removed access to user admin tools for Content Admins
Added temporary method to reset user passwords without needing direct access to DB

Admin panel additions

---

ui_components/src/topbar/Topbar.css

Shortened view:
Full view is hover-only.

Training Notif Hover

---

classes/battle/Battle.php

Academy jutsu should still be subject to the hand sign penalty, just not the cross-offense penalty.

Academy Handsigns

---

classes/System.php
classes/village/VillageApiPresenter.php
classes/village/VillageManager.php
classes/village/VillagePolicy.php
classes/village/VillageSeatDto.php
pages/premium_shop.php
style/sumu/sumu.css
templates/premium/character_changes.php
templates/villageHQ.php
ui_components/build/village/Village.js
ui_components/src/village/Village.css
ui_components/src/village/Village.js

Kage Record + Sumu Updates

---

templates/battle/battle_interface.php

Battle Details Toggle

---

classes/System.php
index.php
style/new_geisha/new_geisha.css
style/sumu/sumu.css
templates/header.php
templates/home.php
ui_components/build/header/Header.js
ui_components/build/home/Home.js
ui_components/src/header/Header.css
ui_components/src/header/Header.js
ui_components/src/home/Home.css
ui_components/src/home/Home.js

- Fixed homepage maintenance mode message
- Patched reputation reset timer bug on day of reset
- Added support for auto-opening and closing based on expected start & end time
- Support for manual closing for an unknown time frame is still support through system vars

Homepage messages & server maintenance

---

classes/village/VillageManager.php
ui_components/build/village/Village.js
ui_components/src/village/Village.js

- Made restrictions clear in the trade UI
- Fixed caravans / patrols not updating on region trade
- Implemented a cooldown period for offering trades

Trade Fixes

---

ui_components/build/topbar/Topbar.js
ui_components/src/topbar/Topbar.css
ui_components/src/topbar/Topbar.js

Sort Training Notifs

---

classes/chat/ChatManager.php

Decrease limit by 50 (550 -> 500) to use as buffer for posts that increase in length on submit due to formatting.

Chat Buffer

---

classes/battle/Battle.php
classes/battle/BattleLog.php
classes/battle/BattleManager.php
db/migrations/20240114112756_battle_log_round_migration.php
pages/viewBattles.php
templates/battle/battle_interface.php
templates/view_battles/battleHistory.php

- Use 2D array for fighter health
- Update columns, use SMALLINT(6) and default value of 1 for `round_number`
- Add `round_number` to `battle_logs` and update indexes
- Update battle history display for rounds
- Fix warnings on undefined avatar size

Battle Log / Round Compatibility and Tweaks

---

classes/battle/Battle.php

Make hand seal functionality consistent between players

Player2 Hand Seal Fix

---

classes/UserReputation.php
classes/training/TrainingManager.php

Responding to concerns over arena gains at Chuu/Jon due to increased pool cost.
Before:
Academy/Gennin: 1/2/4
Chuunin/Jonin: 1/2/4
Sennin: 1/2/4
After:
Academy/Gennin: 1/2/4
Chuunin/Jonin: 1/3/6
Sennin: 1/4/8

Arena Gains

---

classes/ForbiddenSeal.php
pages/arena.php
pages/missions.php
ui_components/build/topbar/TopbarNotification.js
ui_components/src/topbar/TopbarNotification.js
ui_components/src/travel/Travel.css

Stat gain format
Chat message length fix
Training/transfer notif format
Travel message display
Link back to travel on faction mission completion

Misc Fixes

---

admin/entity_constraints.php
classes/Item.php
classes/Route.php
classes/Router.php
classes/Village.php
classes/battle/Battle.php
classes/travel/TravelManager.php
config/routes.php
db/migrations/20240111181343_item_quantity_migration.php
pages/gear.php
pages/healingShop.php
pages/store.php
templates/gear.php
templates/store.php

- Pre-Heal to 95%
- Healing items are now a %
- Cap out of combat healing to pre-heal limit
- Added configuration for per-item carry limit
- Reworked router logic so we can configure conditional overrides for particular pages that are otherwise set to "only in village".

Pre-Heal Update

---

classes/village/VillageManager.php
ui_components/build/village/Village.js
ui_components/src/village/Village.css
ui_components/src/village/Village.js

Update Vote Logic

---

classes/System.php
secure/vars.sample.php
ui_components/build/chat/Chat.js
ui_components/build/chat/Chat_new.js
ui_components/src/chat/Chat.js
ui_components/src/chat/Chat_new.js

Fix chat ban displays

---

classes/village/VillageManager.php

Fix players being able to resign while challenged and let their friends claim the seat before the challenger.

Fix Challenge Exploit

---

pages/team.php

Fix seal loading on teams page

Change seal load

---

style/sumu/sumu.css

Chat Colors

---

ui_components/build/utils/modal.js
ui_components/build/utils/modalContext.js
ui_components/src/utils/modal.js
ui_components/src/utils/modalContext.js

Step 1: import
Step 2: use hook
Step 3: apply modal context via ModalProvider
Step 4: open modal

Modal Component

---

classes/Auth.php

Fixes new & existing location auto-unlock bug

Lockout fix

---

classes/village/VillageBuildingConfig.php
classes/village/VillageUpgradeConfig.php

Config files with all building/upgrade data

Village Config Files

---

classes/village/VillageBuildingDto.php
classes/village/VillageUpgradeDto.php
classes/village/VillageUpgradeManager.php
classes/village/VillageUpgradeSetDto.php

Dto classes and VillageUpgradeManager

Village Upgrade Classes

---

api/village.php
classes/village/VillageApiPresenter.php
classes/war/WarLogDto.php
classes/war/WarLogManager.php
classes/war/WarRecordDto.php
templates/villageHQ.php
ui_components/build/village/Village.js
ui_components/build/village/WarTable.js
ui_components/src/village/Village.js
ui_components/src/village/WarTable.css
ui_components/src/village/WarTable.js

War Table Updates

---

classes/StaffManager.php
db/migrations/20231222060849_mod_stats.php
pages/modPanel.php
templates/staff/mod/ban_confirm.php
templates/staff/mod/head_mod_menu.php
templates/staff/mod/mod_menu.php
templates/staff/mod/mod_stats.php
templates/staff/mod/mod_stats_date_select.php
templates/staff/mod/verbose_mod_stats.php

Add 3-day to all ban types
Add 30-minute and 60-minute ban types to Chat and PM bans
Added basic moderator stats tool to be able to review staff actions
Added detailed data for in-depth reviews

Mod activity

---

classes/Effect.php
classes/battle/BattleEffectsManager.php
classes/battle/BattleManager.php
classes/battle/Fighter.php
templates/battle/battle_interface.php

Effects Display
