elementum-games/shinobi-chronicles

privateMessages.php
-modified 1 line in try catch function
*not sure if removing an exception line is the right way to do it, but it works, I think...
_sent with empty subject line_
=> If Subject empty || less than 2 -> 'No Subject' in PM Subject Column

travel.php
When attempting to move before entering combat for a mission, the mission ends as if a combat draw occurs and tells the user to go back to the village.
Halves the yen gain that they have accumulated so far when they return to the village.
Coincidentally also closes #132
=> Prevents user from continuing a combat mission outside the initial location

pages/battle.php, pages/missions.php
Updated logic for survival missions to account for PVP combat while carrying out the mission. If player wins the PVP fight they can continue with the mission, however if they lose the mission will be considered a retreat and standard logic will be processed. Additionally, code was added to check if the player is supposed to be in survival combat but is somehow in the village (result of a defeat or otherwise) this was mainly added to prevent users already spamming the mission since the new check won't retroactively clear mission ids.
=> Bug Fix - Prevent Survival Mission Spam in Village

pages/profile.php
#217 - This isn't actually a bug, the server side code for applying regen actually applies 2:1 for health and a 1:1 the other stats. The display refresh code doesn't account for this thus it appears that you are getting regen twice for health except it's just on page refresh it properly pulls the value from the player object.
=> Regen Display Fix

templates/battle/battle_interface.php
User Stats are aligned left on the arena page, I added a <div> container surrounding the pools and aligned them center using inline css - its not a huge change but visually it might make the arena page a little more organized.
I didn't do a lot of testing to see if it works for all ranks and scenarios. I tried the arena a few times and it seems to be working on my local, but I had to surgically move the code from another branch into this fresh one so if there's any errors it might be because of that.
=> User Stats/Pools are aligned Center on Arena Page

manual.php
- Fix minor typo on the manual page in the training section
=> Fix minor typo in manual

classes/battle/BattleManager.php
BattleManager.parseCombatText now takes into account separate gender values for attacker/target.
Addresses bug where evasion battle text pronoun varies based on which fighter initiates combat.
e.g. [male] attacks [female]: "[female] cast her jutsu before..."
e.g. [female] attacks [male]: "[female] cast his jutsu before..."
=> Cast Speed evasion text gender fix.

templates/premium/premium.php
Initializes display text using existing javascript. Also moves inline script after table element.
=> Fix for inaccurate initial stat transfer cost

classes/battle/BattleEffectsManager.php
Effect value for speed/cspeed nerfs uses a percentage unlike other nerfs which use a flat value based on damage. This makes them disproportionately affected by debuff resist and leads to using the minimum effect value (1/10th base effect).
=> Adjust speed/cspeed nerfs to ignore debuff resist

classes/battle/BattleEffectsManager.php
Adds cripple to the `BattleEffectManager.setEffect()` effect list. 
Previously unlisted and defaults to `$apply_effect = false;`
Users report this was working previously, I'm not sure if something else broke at some point but this is the apparent fix.
=> Enable cripple effect

classes/Bloodline.php, classes/battle/BattleEffectsManager.php, classes/battle/Fighter.php
Suggested changes: 
- Simplifies bloodline/offense calculation so that players need only keep bloodline and offense skills equal for optimal stat allocation rather than keeping bloodline stat exactly 110 points ahead. 
- Factors in bloodline speed/cspeed bonus for speed buff/nerf calculations. Bloodline speed bonuses being immutable is interesting but unintuitive. It also creates balance problems, particularly when speed-focused players benefit less from the use of speed boosts.
=> Adjust bloodline stat calculations for transparency

index.php
I'm confused as to why `!empty($_GET['act'])` is necessary for this to work for resend verification but `!empty($_POST['act'])` has apparently been working for the verification link, so this could use a second look and test on dev before deployment.
=> Fix verification

classes/battle/BattleManager.php, classes/battle/Fighter.php, templates/sensei_exam.php
Prior speed change before was calculated at a 4% increase in damage for balance builds and 10% increase in damage for speed builds. New change equates to a 0% increase in damage for balance builds and a 6% increase in damage for speed builds (over the original baseline before prior changes).
Speed to Offense Ratio: 0.35 -> 0.25 (reverting prior change)
Evasion Ratio: 0.4 -> 0.47
Percent required to reach maximum evasion: 87.5% -> 75%
Original Speed Build:
50k Bloodline -> 60000 Offense
50k Offense Stat -> 50000 Offense
150k Speed Stat -> 37500 Offense
Total: 147500
0.25 -> 0.35 Buffed Speed Build (Old):
50k Bloodline -> 60000 Offense
50k Offense Stat -> 50000 Offense
150k Speed Stat -> 52500 Offense
Total: 162500 (+10% total, +6% over Balance)
New Speed Build:
55k Bloodline -> 66000 …
=> Speed Rebalance

classes/notification/Notifications.php, classes/travel/TravelManager.php, classes/village/VillagePolicy.php, classes/war/Operation.php, classes/war/WarManager.php, cron_jobs/region_cron.php, ui_components/build/village/Village.js, ui_components/src/village/Village.js
- Removed 60s immunity from being attacked after a loss
We already have the 5-min immunity so this is doubling up, and it causes issues in war when someone does war actions during the immunity.
- Added battle links for old layouts
- Fixed caravan name on region change
=> War Tweaks

classes/ForbiddenSeal.php, classes/PremiumShopManager.php, pages/premium_shop.php, templates/premium/premium.php
Added Eight Trigram seal
Benefits:
+25% Regeneration rate
Longer journal (3500 characters)
Journal image size of 600x600
Enhanced long trainings (1.5x length, 2.2x gains)
Enhanced extended trainings (2x length, 3x gains)
Faster stat transfers(+6/minute)
View logs of your last 50 battles
Comparison to T2 seal
+5% Regeneration rate
+1000 journal characters
+100x100 journal image size
Long trainings +20% gains
Extended trainings +25% length, +50% gains
+1 stat/minute transfer
+30 battle log history
Update comes with a seal sale, ends Nov 30:
Upgrading to T3 seal from T1 or T2 will provide a 50% refund, if any credit exists over the purchase price. Estimated refunds will be displayed in the purchase confirmation screen.
=> Added Eight Trigram

classes/UserReputation.php, classes/war/Operation.php, classes/war/WarManager.php
Loot/Reinforce/Infiltrate/Raid
Chuu: 0/2/3/4 
Jonin: 0/3/4/5
Resource Gains
Loot / 10 = Stat Gain
Loot / 10 = Rep Gain
e.g. 1 stat per loot action, 1 bonus stat per 2 Infiltrates
======================
Reinforce/Hour
Lv50 Chuunin: 46/hour
lv100 Jonin: 75/hour
Infiltrate/Hour (w/ loot)
lv50 Chuunin: 80/hour
lv100 Jonin: 112.5/hour
Raid/Hour
lv50 Chuunin: 92/hour
lv100 Jonin: 125/hour
Short/Hour
Chuunin, no bonus: 96/hour
Chuunin, clan + team: 113/hour (9min with 6% increased gains)
Jonin, no bonus: 120/hour
Jonin, clan + team: 141/hour (9min with 6% increased gains)
Special Mission (Normal)/Hour 
Chuunin: 102/hour (3.5min for 6 stats)
Jonin: 137/hour (3.5min for 8 stats)
Special Mission (Nightmare)/Hour
Chuunin: 133/hour (4.5min for 10 stats)
Jonin: 160/hour (4.5min for 12 stats)
=> War XP Rebalance

admin/constraints/bloodline.php, admin/constraints/jutsu.php, admin/entity_constraints.php, classes/Bloodline.php, classes/battle/Battle.php, classes/battle/BattleEffect.php, classes/battle/BattleEffectsManager.php, classes/battle/BattleManager.php, classes/battle/Fighter.php, pages/bloodline.php
[Evasion Changes]
Speed/CSpeed converts to evasion (for their respective offense type) based on ratio to stat total.
- 0% investment = 0% evasion
- 35% investment = 35% evasion
- 50% investment = 50% evasion
Soft cap at 50%
Hard cap at 75%
Soft cap ratio 50% (any evasion higher than the soft cap is only 50% as effective)
Final evasion is calculated by comparing the evasion stat of both players. 
If Player 1 has 35% evasion, and Player 2 has 10% evasion, the end result is Player 1 with 25% evasion.
Evasion calculation factors in the difference between user's and opponent's stat total.
- e.g. Fighting an opponent with half of your stat total doubles your total evasion. 
- if it was based on your own stat total, gaining non-speed stats decreases your evasion
- if it was based on your own …
=> Evasion Rework / Bloodline Bonuses

classes/battle/BattleEffectsManager.php, classes/battle/BattleManager.php
- Evasion Soft Cap: 50% => 35%
- Evasion Hard Cap: 50% => 65%
- Cripple: now works correctly (modifies Evasion)
Addresses issues with balance between high speed and low speed.
Expectations based on additional testing:
30/10 BL vs 25/20 BL = identical
80k/80k/90k vs 62.5k/62.5k/125k = identical
80k/80k/90k vs 125k/125k/0 = identical
Speed vs Resist BL = identical
After changing Evasion soft cap from 50% down to 35%:
125/125/0 vs 62.5/62.5/125 = identical
Note: 80/80/90k === 80k Bloodline Skill, 80k Offense Skill, 90k Speed/CSpeed
=> Speed Adjustments

classes/Bloodline.php
Tuning bloodline bonuses to meet the following goals:
- Speed and Resist should result in equal match-ups when all other variables are accounted for
- Offensive and Defensive bloodlines should result in equal match-ups, regardless of bloodline investment
- e.g. a Resist bloodline with 30 Off should have an even matchup against a Resist bloodline with 25 Off
- this should remain true for high (250k) and average (90k) bloodline skill
- Builds with high bloodline investment should deal consistently less damage with shop jutsu
- bloodline builds should fall behind in damage at a similar same rate against a balance build when using shop jutsu
- if these values don't line up perfectly we can tune BL jutsu on a per-bloodline basis to account for it
Editor Changes:
- 25/20 BLs => 25/18
- Based on …
=> Bloodline Tuning

admin/constraints/jutsu.php, admin/entity_constraints.php, classes/Jutsu.php, classes/battle/BattleActionProcessor.php, classes/battle/BattleAttack.php, classes/battle/BattleEffect.php, classes/battle/BattleEffectsManager.php, classes/battle/BattleManager.php, classes/battle/Fighter.php, classes/notification/NotificationAPIManager.php
- Add "Reflect" tag, essentially a Counter that turns incoming damage into a residual
- Will lean into the Genjutsu playstyle of using residuals as a resource to empower other jutsu
- Add "Delayed Residual" tag, effectively Piercing but for jutsu with lower base power (e.g. Lightning Genjutsu)
- Reworked Immolate to ONLY convert residuals into power for the jutsu
- Keeps Genjutsu more interactive so both players can play around Immolate effects
- Lets us use Immolate as more than a combo finisher, residuals become a resource
- Capped Counter/Reflect damage to that of the counter
- e.g. a Counter that deals 30k direct damage can only deal 30k additional counter damage (in terms of raw damage)
- Fixed elemental tags
- Fixed bug that could cause players to be stuck in combat
Idea behind …
=> Combat v1.2 updates 4

style/new_geisha/new_geisha.css, style/sumu/sumu.css, templates/battle/action_prompt.php, templates/battle/battle_interface.php
- new button at top (same bar as refresh battle) jumps you straight to the jutsu select
- double clicking a jutsu uses the jutsu
- fixed weirdness with jutsu text overflowing
- clicking taijutsu adds the overlay thing to the hand seal rather than making the page jump up/down
- hand seal overlay now uses the same color as the container rather than blinding white
=> battle qol

classes/chat/ChatManager.php, classes/user/Blacklist.php
Added method to add blacklist data to table for new users
A blocked user mentioning/quoting you in chat no longer sends notifications
Quotes that are deleted, or blocked by viewing user, are now just stripped from the chat post (i.e. no longer displays "_(removed)_")
=> Fix for new users to add BL data to table

classes/travel/TravelManager.php
Use existing travel message logic to display "normal" exceptions rather than flooding the error log with uncaught exceptions.
=> Handle Travel Exceptions

classes/battle/BattleEffectsManager.php
- Fixed issue that would cause subsequent barriers to overwrite the secondary effect of the previous barrier
- Reduced visual clutter under effect display (e.g. "Reflect Damage" and "Reflect" as debuffs from the same jutsu)
=> Effect Cleanup

classes/PremiumShopManager.php
Increase baseline to 250 for Genin to prevent soft-locking themselves with weird stat spreads.
=> Free Transfer Minimum

classes/Bloodline.php, templates/battle/action_prompt.php
- Display bloodline jutsu in rank order
- Fix issue where bloodline jutsu would show the actual power of the residual damage after use instead of the % (e.g. 478437 instead of 25%)
=> Bloodline Jutsu Display

api/battle.php, classes/battle/Battle.php, classes/battle/BattleManager.php, classes/battle/BattleV2.php, classes/village/VillageManager.php, db/migrations/20240108071157_battle_round_migration.php, templates/battle/battle_interface.php
- Adds optional parameter to battle initialization
- Battles have rounds, tracks winner of each round and resets to clean state at start of next
- Winner declared if sufficient wins reached (e.g. 2 wins in a 3 round battle will skip the 3rd round)
- If tied by end of round limit, will add additional rounds until the next win
- Challenges are now set to 3 rounds
- Reputation bonus for challenges from 15% -> 5%
=> Battle Rounds

classes/travel/NearbyPlayers.php
Limit for pagination on scouting page is cutting off lower rank players, the query only looks at the top X online players. Since there's never a case where the spar list is large enough for pagination, I'm just removing the restriction so Chuunin and Genin can actually spar each other.
=> Fix Spar Scouting

classes/battle/BattleManager.php
Normalize barrier strength against Genjutsu, typically set to 62.5% of Tai/Nin.
=> Enable Genjutsu barrier penalty

templates/view_user_profile.php
add elements to display on profile
moved around a few rows
added number_format
spouse no longer displays if user has no spouse
with spouse:
without spouse:
=> updated user profile displays
